services:
  reuters:
    build:
      context: .
      dockerfile: Dockerfile
    tty:  true
    stdin_open: true
    container_name: reuters.local
    working_dir: /src/Reuters
    command: 'python App.py'
    volumes:
      - .:/src/Reuters